#+Title Sunday is a busy day


** In the saddle

We got up fairly early for a Sunday this morning and went for a longish (for us) bike ride. So far today I have put in about 9 miles. No, it is nowhere near the amount of miles I used to put in on a ride but they were super enjoyable miles. I had forgotten the simple joy of being out for a ride in the early hours of the morning just spinng the crank and trying to get the heart rate up. I have no ambitions of being a racer anymore or trying to trek acroos the country or anything like that. I just want to ride.

I am doing this mostly for my health. We really don't get just gobs of exercise. Yes, I am in a rather physical job but it really doesn't get the heart rate up and doing the job is becoming more painful with each passing year. Doing my job hurts enough now that I am not sure that I will last much longer in it. I am falling apart.

I doubt cycling is going to fix that but it is a very nice stress breaker. I am relaxed in the saddle. I guess it is just being outside doing something and having the sun and wind on your skin, I don't know.

After the ride and checking the all the cyber crap that I wear and carry while exercising I discovered that I am not getting my heart rate up to the aerobic level. Well, I can hit aerobic and anaerobic levels I just don't know how to maintain them for any length of time. In an hour long ride today the heart rate hit aerobic levels for only five minutes and anerobic for five minutes. My understanding is that I need more of an aerobic work out. Got to study up on how to do that. Simply put, I just don't know how. 

** Tech stuff 

Mostly due to being sick and tired of seeing AI generated slop and egregious privacy violations I am retreating from most of the popular online schlock that is out there. No mas using of Meta or Alphabet products and I am returning to FOSS software for the most part. Now for those that don't speak geek what that means is that I won't be showing up on Facebook, Instagram, Threads, Google Meet, Twitter, What'sApp, etc and et al.

Most of my online presence will be this [[https://ragamuffinjim.github.io][blog]], [[mailto:ragamuffinjim@gmail.com][email]], RSS feeds, and a Matrix account (@ragamuffinjim:matrix.org)for instant messaging and [[https://mastodon.social/@ragamuffinjim][mastodon]] account for microblogging.

I do have to keep a Google presence for work purposes and that is, coincidentally, my email too,. I have yet to figure out what to do with my burgeoning YouTube empire (HAHA) but everytime I get on the poplar sites I am just disgusted by them and want little to nothing to do with them.

So, a large part of the rest of today will be the tweaking of things in my new empire. Say hello to your new geek overlord HEHEHE!
