#+Title: Playing with Org-Mode Again
#+Author: James D. Morgan
#+Email: ragamuffinjim@gmail.org

* Playing With Emacs Again

Due to changes at work I have found myself in a new office. I moved my stuff in and setup my computer.For some reason when I booted up my computer I turned on Emacs and began playing aound with it again. I am not sure why but that is what happened. 

On my tablet I have the [[https://f-droid.org/packages/org.gnu.emacs/][Emacs for Android]] app loaded and sometimes running. When I got home I thought to myself that it would be nice to have my phone, tablet, work computer, and personal computer all running the same stuff and I got to thinking that Emace might be the ticket to do this.

* Email /might/ be an issue

I paused for a moment and realised that send and receiving email might be an issue on the Android. Not sure how I will be able to set up the mailbox and sundries on ANdroid. I am not saying that it is not possible, I am just saying that I am not sure how to do it at this point.

* But other stuff works...

Even on the Android app things like Elfeed, Mastodon, and Org-Mode work well. Not sure about Magit for git. I will try it out later and see if it works.

* So the vision at this point 

So a small vision has entered my noggin about using Emacs exclusively for alot of the things that I do. 

** RSS

My feed reader for the time being will be Elfeed on all devices.

** Blog

I am currently redesigning the blog to be simpler to use. Rather than this complicated mess that I do now I will just write an article in [[https://orgmode.org][Org-Mode]], then send it to Github to do all the converting into a nice little webpage and creating an RSS feed.

** Git

I have just started using [[https://magit.vc][Magit]] so I am not sure how it all works but if I can figure it out then Magit will be what I use for git operations. Git has been one of the workhorses for this blog since the beginning. Now I am addicted. I have to use git.

** Emacs

[[https://en.wikipedia.org/wiki/Emacs][Emacs]] will be the backbone of the entire operation. Emacs come packaged with most of the essentials of modern life. Calendars, calulators, games, editor ... all come with the download. And orgmode is so amazing that I doubt anyone has enough of a life to fully implement all of it.

** Social Media

Email is my preferred social media, believe it or not. However I do have an acoount on Mastodon that I play with from time to time. I will use the mastodon app in Emacs for this purpose.

** Email

Email, my preferred communication tool, will be handled in Emacs with mu/mu4e on the computers. For the time being the stock app on the phone and app will have to suffice.

* Lots of leftovers

I am not sure about a lot of things- like multimedia stuff, web browsers etc. I don't want to bite off more than I can chew so my priorities will be orgmode blogging thing and magit. The other things are nice to haves.

[[index.org][Home]]

[[mailto:ragamuffinjim@gmail.com?subject=Playing-with-Emacs][Reply by Email]] 
